## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.7
  - 1.0
notifications:
  email: sunbergzach@gmail.com
git:
  depth: 99999999

script:
  - git clone https://github.com/JuliaRegistries/General  $(julia -e 'import Pkg; println(joinpath(Pkg.depots1(), "registries", "General"))')
  - git clone https://github.com/JuliaPOMDP/Registry  $(julia -e 'import Pkg; println(joinpath(Pkg.depots1(), "registries", "JuliaPOMDP"))')
    # - julia -e 'import Pkg; Pkg.add("POMDPs"); import POMDPs; POMDPs.add_registry()'
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --project --color=yes --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("ARDESPOT"; coverage=true)'

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("ARDESPOT")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("ARDESPOT")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
